name: umap_legacy
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=2.7
  - bowtie
  - samtools
  - ucsc-bedgraphtobigwig
  - ucsc-wigtobigwig
  - numpy
  - pandas
# After creating: git clone https://github.com/hoffmangroup/umap && (cd umap && git checkout 1.2.1)
